sudo: required
services:
  - docker

before_install:
  - docker build -t umadiraju/react-test -f ./client/Dockerfile.dev ./client

script: 
  - docker run umadiraju/react-test npm test -- --coverage

after_success: 
  - docker build -t umadiraju/multi-client ./client
  - docker build -t umadiraju/multi-nginx ./nginx
  - docker build -t umadiraju/multi-server ./server
  - docker build -t umadiraju/multi-worker ./worker
  # Login to the docker CLI
  
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Take those images and push them to docker hub
  - docker push pathi7/multi-client
  - docker push pathi7/multi-nginx
  - docker push pathi7/multi-server
  - docker push pathi7/multi-worker






